ALTER TABLE story_project
    ADD COLUMN genre_code VARCHAR(64) NOT NULL DEFAULT '',
    ADD COLUMN characters_json JSON NOT NULL DEFAULT (JSON_ARRAY()),
    ADD COLUMN word_count_json JSON NOT NULL DEFAULT (JSON_OBJECT());